# Generated by Django 3.2.4 on 2021-06-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20210617_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usta',
            old_name='email',
            new_name='eposta',
        ),
    ]
